<a href="https://colab.research.google.com/github/UMANG13-coder/CE154_ML/blob/main/Lab_3/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB, CategoricalNB

In [ ]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']


In [ ]:
le = preprocessing.LabelEncoder()

weather_encoded = le.fit_transform(weather)

print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [ ]:
temp_encoded = le.fit_transform(temp)

print(temp_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [ ]:
label = le.fit_transform(play)
print(label)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
features = tuple(zip(weather_encoded,temp_encoded))
print(features)

((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
model = CategoricalNB()
model.fit(features,label)


CategoricalNB()

In [ ]:
prediction = model.predict([[0,2]])
print(prediction)

[1]


In [ ]:
prediction = model.predict([[0,1]])
print(prediction)

[1]


In [ ]:
prediction = model.predict([[2,2]])
print(prediction)

[0]


In [ ]:
model = MultinomialNB()

model.fit(features,label)

MultinomialNB()

In [ ]:
predicted = model.predict([[0,1]]) #0:overcast,1:Hot
print("Predicted Value:",predicted)

predicted= model.predict([[2,2]]) #2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]


In [ ]:
import numpy as np
from sklearn import datasets

#Load dataset
iris = datasets.load_iris()

In [ ]:
newdata = iris.data[50:,:]
newtarget = iris.target[50:]

In [ ]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test = train_test_split(newdata,newtarget,test_size=0.30,random_state=4)

In [ ]:
gnb = GaussianNB()
gnb.fit(data_train,target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9333333333333333


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test,target_pred)

array([[15,  2],
       [ 0, 13]])

In [ ]:
from sklearn.metrics import precision_score,recall_score
precision = precision_score(target_test,target_pred)
print('pricision: {}'.format(precision))
recall = recall_score(target_test,target_pred)
print('recall: {}'.format(recall))

pricision: 1.0
recall: 0.8823529411764706


Exercise

Task 1

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/ML/LAB3/Dataset3.csv")
outlook = data['Outlook'].values
temp = data['Temp'].values
wind = data['Wind'].values
humidity = data['Humidity'].values
print("Outlook: ",outlook)
print("Temp: ",temp)
print("Wind: ",wind)
print("Humidity: ",humidity)

Outlook:  ['R' 'R' 'O' 'R' 'S' 'O' 'O' 'R' 'O' 'S' 'R' 'O' 'O' 'S']
Temp:  ['H' 'H' 'H' 'M' 'C' 'C' 'C' 'M' 'C' 'M' 'C' 'M' 'H' 'M']
Wind:  ['F' 'T' 'F' 'F' 'F' 'T' 'T' 'F' 'F' 'F' 'T' 'T' 'F' 'T']
Humidity:  [1 2 1 1 1 0 1 1 0 2 2 0 1 1]


In [ ]:
le = preprocessing.LabelEncoder()
enc_outlook = np.array(le.fit_transform(outlook))
enc_temp = np.array(le.fit_transform(temp))
enc_wind = np.array(le.fit_transform(wind))
target = np.array(data['Class'].values)
print("Outlook: ",enc_outlook)
print("Temp: ",enc_temp)
print("Wind: ",enc_wind)

Outlook:  [1 1 0 1 2 0 0 1 0 2 1 0 0 2]
Temp:  [1 1 1 2 0 0 0 2 0 2 0 2 1 2]
Wind:  [0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [ ]:
features = tuple(zip(enc_outlook,enc_temp,enc_wind,humidity))
X_train,X_test,y_train,y_test = train_test_split(features,target,test_size=0.05,random_state=154)
print("X_train is : ",X_train)
print("y_train is : ",y_train)

X_train is :  [(2, 2, 1, 1), (0, 0, 0, 0), (1, 2, 0, 1), (2, 0, 0, 1), (0, 1, 0, 1), (0, 2, 1, 0), (0, 1, 0, 1), (1, 1, 0, 1), (1, 1, 1, 2), (1, 0, 1, 2), (1, 2, 0, 1), (0, 0, 1, 0), (2, 2, 0, 2)]
y_train is :  [0 1 0 1 1 1 1 0 0 0 1 0 1]


In [ ]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
target_pred = gnb.predict(X_test)

In [ ]:
print("Accuracy: ",metrics.accuracy_score(y_test,target_pred))

Accuracy:  0.0


Task 2

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/ML/LAB3/breast_cancer_wisconsin.csv")
dataset = dataset.iloc[:,1:]
target = np.array(dataset['diagnosis'].values)
features = np.array(dataset.iloc[:,1:-1].values)
print("Target: ",target)
print("Features: ",features)

Target:  ['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M'
 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' '

In [ ]:
ohe = preprocessing.OneHotEncoder()
target = ohe.fit_transform(target.reshape(-1,1))
s = target.toarray()
target = np.array(s[:,0],dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(features,target,test_size=0.5,random_state=154)
type(y_train)

numpy.ndarray

In [ ]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
target_pred = gnb.predict(X_test)

In [ ]:
print("Accuracy: ",metrics.accuracy_score(y_test,target_pred))

Accuracy:  0.9473684210526315
